events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name 173.249.28.153; 

        # Frontend (Angular SSR)
        location / {
            proxy_pass http://angular:4000; # Cambia al puerto interno que use tu SSR (4000 o 3000)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Backend Transaccional (Spring Boot)
        location /api/v1/ {
            proxy_pass http://springboot:8080/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Microservicio de IA (FastAPI)
        location /api/chat/ {
            proxy_pass http://fastapi:8000/; # Ajusta el puerto base si FastAPI expone otra ruta interna
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}